on:
  workflow_dispatch:
    

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          CHROME_VERSION=$(google-chrome --product-version)
          echo "Chrome version: $CHROME_VERSION"
          CHROME_VERSION=${CHROME_VERSION%.*}
          echo "Short Chrome version: $CHROME_VERSION"
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
          
          CHROME_VERSION=$(google-chrome --product-version)
          echo "Chrome version: $CHROME_VERSION"
          CHROME_VERSION=${CHROME_VERSION%.*}
          echo "Short Chrome version: $CHROME_VERSION"
